-d D:\Elektronika\FPGA\projekty\Tang_nano\blink_led\impl\gwsynthesis\blink_led.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst D:\Elektronika\FPGA\projekty\Tang_nano\blink_led\src\pin.cst
-cfg D:\Elektronika\FPGA\projekty\Tang_nano\blink_led\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
